### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cantino** [arty-name/livejournal-export#1]
Just wanted to say thanks, this was helpful for me!  I had to add `encoding: 'utf8'` a bunch of places, but otherwise it worked perfectly.

**Comment by arty-name** [comment]
I am glad to hear that! 

BTW, do you want to submit a pull request with encoding fixes?

**Comment by cantino** [comment]
I already deleted my journal after exporting it,  so I can't test, but all
I did was add "encoding: 'UTF8'" after every file open.

**Comment by UberJason** [comment]
I realize the low odds here given that this project is 2 years old, but can you give any more details as to where to add `encoding: 'utf8'`? I'm not a Python dev normally, and think I'm running into the same issue. I get an error `UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 114: ordinal not in range(256)`, which certainly implies an encoding issue.

**Comment by cantino** [comment]
See https://stackoverflow.com/a/6289494

**Comment by UberJason** [comment]
Sadly I tried that already. It only affects Python 2.7, and it seemed like yours was a Python 3 project because of some keyword change from 2 to 3. (Let me know if that was an incorrect conclusion on my part.) I re-ran it in Python 3 and came across the error I mentioned above.

**Comment by cantino** [comment]
I'm not sure, sorry.

**Comment by UberJason** [comment]
That's all right, thanks for trying! May well be the case that other conditions have changed in the last two years that make this script no longer work.

**Comment by arty-name** [comment]
@UberJason this is definitely Python3, even the hashbangs (first lines of python files) say that. 

If you could provide the  full stacktrace of the error I might be able to fix the issue. So far I can only guess that two years ago @cantino meant something different by "after every file open":

```python
open(path, modifier, encoding="utf-8")

**Comment by cantino** [comment]
Oh yes! That is what I did.

**Comment by arty-name** [comment]
@UberJason, could you try this branch? https://github.com/arty-name/livejournal-export/tree/file-encoding

**Comment by UberJason** [comment]
Worked beautifully! Thanks!

**Comment by arty-name** [comment]
And thank you for confirming it works. I will merge the change in the master branch then.
