### ISSUE TITLE
LJ language option and parser warning.

### ISSUE THREAD

**Issue by Hexadecimalism** [arty-name/livejournal-export#12]
Generated HTML files use "Комментарии" (Russian) instead of "Comments" (English) as an English speaker. There must be a way to set language settings somewhere.

In addition it throws up this warning

> drive\location\lj\export.py:54: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
> 
> The code that caused this warning is on line 54 of the file drive\location\lj\export.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.
> 
>   slug = BeautifulSoup('<p>{0}</p>'.format(slug)).text

Code might need to be more explicit.

**Comment by arty-name** [comment]
Thank you for reporting this!

Since running this code requires quite some computer literacy anyway, the "translation" henceforth can be done by modifying the value of `COMMENTS_HEADER` in the export.py.
