### ISSUE TITLE
Question and thanks

### ISSUE THREAD

**Issue by angiioh** [arty-name/livejournal-export#15]
Thanks for making this! I finally stopped procrastinating on my exporting my old 2002-12 journal and this was the only tool for that that still seems to work.

I do have a question though: Is it possible to include the Current Mood and Current Music info in the markdown versions? If so, how? 

Thank you!

**Comment by arty-name** [comment]
These fields would be available as `current_mood` and `current_music` on the `json` object. You’d have to modify the `json_to_markdown` function in `export.py` to include these values in a way you want to have them.

**Comment by angiioh** [comment]
Okay, sounds good. Thanks so much :]

**Comment by angiioh** [comment]
Okay, sounds good. Thanks so much :]

**Comment by arty-name** [comment]
Happy to help!
