### ISSUE TITLE
Outdated String Formatting \s

### ISSUE THREAD

**Issue by dsnvwlmnt** [arty-name/livejournal-export#16]
FWIW Python 3.12 gives a syntax warning, which to my understanding in a future Python version will be a syntax error:

> export.py:19: SyntaxWarning: invalid escape sequence '\s'
>   NEWLINES = re.compile('(\s*\n){3,}')
> 

I'm not sure what effect this had on my exported blog... A cursory look seems to be fine...

There are 2 solutions listed here: https://stackoverflow.com/questions/50504500

Either 1) declare it a string literal by putting an _r_ in front: `r'(\s*\n){3,}'`
Or 2) _maybe_ you can double escape the _s_: `'(\\s*\n){3,}'`

I'm a little out of my depth to say more.

**Comment by arty-name** [comment]
Thank you for your very detailed input!
