### ISSUE TITLE
Script killled with "Out of memory"

### ISSUE THREAD

**Issue by arty-name** [arty-name/livejournal-export#3]
Reported by Aleksandr Nessler:

I’m trying to download the blog with 2000 posts & over 250000 comments, and i get the running script ‘killed’ while trying to create the json version with all the comments.

I tryed to limit the ammount of processed posts+comment by setting the start-end YEAR, but this parametter does not affect comments, as i can see. It affects only posts.

Probably there shall be limit for the data raised to memory to create the structure for json_export.

**Comment by arty-name** [comment]
Do you get any stacktrace when that happens? Are you running the script in a virtual machine?

**Comment by arty-name** [comment]
Also, how many files do you see in `comments-xml` folder? Since every XML contains around 1000 comments, you should get around 250 files.

**Comment by raidho** [comment]
291 file in `comments-xml` folder

I use basic vm hosted by hetzner with 512mb RAM to run the scripts. 

I any case, i suppose that all posts with comments razed to memory at once to dump-json are just bigger than 512mb.

**Comment by arty-name** [comment]
Please try replacing line 95:

```
    f.write(json.dumps(all_comments, ensure_ascii=False, indent=2))
```

with this:

```
    json.dump(all_comments, f, ensure_ascii=False, indent=2)
```

**Comment by raidho** [comment]
``````
Traceback (most recent call last):
   File "./export.py", line 194, in <module>
   all_posts = download_posts()
File "/home/raidho/lj_cosh/lj/download_posts.py", line 64, in download_posts
   xml_posts.extend(list(ET.fromstring(xml).iter('entry')))
File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1325, in XML
 parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0```
``````

**Comment by arty-name** [comment]
Hmm, it looks like the problem happens while downloading posts, not comments. That's actually good, I didn't see much room for optimization in the comments downloader.

**Comment by arty-name** [comment]
Could you try [the branch less-ram](https://github.com/arty-name/livejournal-export/compare/less-ram)?

**Comment by raidho** [comment]
Same issue. 
I Will try again on a less resource limited to check the limits.

**Comment by arty-name** [comment]
Does it fail with the same stacktrace?

**Comment by arty-name** [comment]
I guess I can close it now
