### ISSUE TITLE
xml error parsing error in download_posts.py

### ISSUE THREAD

**Issue by skorasaurus** [arty-name/livejournal-export#7]
Hi, 

Thanks for making this; unfortunately I receive the following error when I run `python3 export.py` in a virtualenv that's specifically for this package. I installed requests, beautifulsoup4, markdown, html2text using pip within my virtualenv. 

I also filled out auth.py and ran that first before running export.py. 

I should also mention that I did not have a cookie named ljmastersession but I did have a cookie named ljsession and used its value for ljmastersession.

`Traceback (most recent call last):
  File "export.py", line 194, in <module>
    all_posts = download_posts()
  File "/home/skors/python/livejournal-export/download_posts.py", line 64, in download_posts
    xml_posts.extend(list(ET.fromstring(xml).iter('entry')))
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
`

**Comment by arty-name** [comment]
Hi Will,

Most likely  the parsing has failed because the response was not XML but HTML with error message. I expect the reason for that was failed authorization. You can find both necessary cookies while on https://www.livejournal.com 

You don’t have to run auth.py because it only contains data.

**Comment by skorasaurus** [comment]
Thank you responding back. Your response encouraged me to try once more since I now learned that my error was an authentication error. 
I tried once more with a different firefox profile (no add-ons enabled, a fresh install); the ljmastersession cookie did appear this time; and I use its value and the new value for ljloggedin 
and ran export.py and my entries exported as expected. Thank you :)

**Comment by arty-name** [comment]
Glad to hear that :)
