### ISSUE TITLE
Script gets stuck if there are no comments to download

### ISSUE THREAD

**Issue by dueringa** [arty-name/livejournal-export#9]
First off, thanks for this script.

The following code in download_comments.py gets stuck in an infinite loop if there are no comments at all

~~~ python
    start_id = -1
    max_id = int(metadata.find('maxid').text)

    print("Start getting comments", start_id, "/", max_id)
    while start_id < max_id:
        ...
~~~

start_id is always -1, max_id is always 0.

**Comment by arty-name** [comment]
Thanks for the report! I think I have addressed the issue.
